services:
    web:
        build:
            context: ..
            target: production
        environment:
            - MAIL_SERVER=${MAIL_SERVER}
            - MAIL_PORT=${MAIL_PORT:-587}
            - MAIL_SECURE=${MAIL_SECURE:-true}
            - MAIL_USER=${MAIL_USER:-username}
            - MAIL_PASS=${MAIL_PASS}
            - MAIL_FROM=${MAIL_FROM:-username <email>}
            - MAIL_REDIRECT_URL=${MAIL_REDIRECT_URL:-/auth/confirm#{token}}
            - PROFILE_REDIRECT_URL=${PROFILE_REDIRECT_URL:-/profile/{uuid}}

            - JWT_SECRET=${SERVICE_BASE64_64_JWT_SECRET}
            - ADMIN_TOKEN=${SERVICE_BASE64_64_ADMIN_TOKEN}

            - POSTGRES_DB=${SERVICE_BASE64_POSTGRES_DB}
            - POSTGRES_PASSWORD=${SERVICE_BASE64_POSTGRES_PASSWORD}
            - POSTGRES_USER=${SERVICE_BASE64_POSTGRES_USER}

            - MINIO_ROOT_PASSWORD=${SERVICE_BASE64_MINIO_ROOT_PASSWORD}
            - MINIO_ROOT_USER=${SERVICE_BASE64_MINIO_ROOT_USER}
            - MINIO_DEFAULT_BUCKETS=${SERVICE_BASE64_MINIO_DEFAULT_BUCKETS}

            - SERVICE_FQDN_ADVENT_3000

            - TRUST_PROXY=${TRUST_PROXY:-true}
            - LOG_FOLDER=${LOG_FOLDER:-/logs}
            - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
            - REDIS_HOST=${REDIS_HOST:-redis}
            - MINIO_HOST=${MINIO_HOST:-minio}

        volumes:
            - applogs:/logs
        depends_on:
            - postgres
            - redis
            - minio

    postgres:
        image: postgres:17-alpine
        environment:
            - POSTGRES_DB=${SERVICE_BASE64_POSTGRES_DB}
            - POSTGRES_PASSWORD=${SERVICE_BASE64_POSTGRES_PASSWORD}
            - POSTGRES_USER=${SERVICE_BASE64_POSTGRES_USER}
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:7.4

    minio:
        image: "bitnami/minio:latest"
        environment:
            - MINIO_ROOT_PASSWORD=${SERVICE_BASE64_MINIO_ROOT_PASSWORD}
            - MINIO_ROOT_USER=${SERVICE_BASE64_MINIO_ROOT_USER}
            - MINIO_DEFAULT_BUCKETS=${SERVICE_BASE64_MINIO_DEFAULT_BUCKETS}
        volumes:
            - minio:/bitnami/minio/data

volumes:
    postgres:
    minio:
    applogs:
