services:
    web:
        build:
            context: ..
            target: production
        ports:
            - "0.0.0.0:3000:3000"
        env_file:
            - path: ../.env
              required: true
            - path: ../.env.production.local
              required: true
        volumes:
            - ../logs:/logs
        depends_on:
            - postgres

    postgres:
        image: postgres:17-alpine
        env_file:
            - path: ../.env
              required: true
            - path: ../.env.production.local
              required: true
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:7.4

    minio:
        image: "minio/minio:latest"
        env_file:
            - path: ../.env
              required: true
            - path: ../.env.production.local
              required: true
        volumes:
            - minio:/bitnami/minio/data

volumes:
    postgres:
    minio:
