services:
    web:
        build:
            context: ..
            target: development
        ports:
            - "0.0.0.0:3000:3000"
        volumes:
            - ..:/data/app
        environment:
            NODE_ENV: development
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
        stdin_open: true
        tty: true
        depends_on:
            - postgres

    postgres:
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
        ports:
            - "0.0.0.0:3030:5432" # Use port 3030 for external debugging
        # # Uncomment the next line to have a persistent volume for the database
        # volumes:
        #     - postgres:/var/lib/postgresql/data
