name: Check lint

on:
    push:
        branches:
            - main
            - master
            - develop
    pull_request:
        branches:
            - main
            - master
            - develop
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Check lint
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Check lint
              run: npm run lint
